# Generated by Django 4.1.2 on 2022-10-27 05:11

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
