# Generated by Django 4.1.2 on 2022-10-27 05:22

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_alter_section_section_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="section_name",
            field=models.ManyToManyField(to="departments.section"),
        ),
    ]
