# Generated by Django 4.1.2 on 2022-10-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0004_remove_department_section_name_department_section",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="section",
            new_name="sections",
        ),
    ]
