# Generated by Django 4.1.2 on 2023-02-19 18:37

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("equipment_name", models.CharField(max_length=255)),
                (
                    "equipment_serial_no",
                    models.CharField(max_length=255, unique=True),
                ),
                ("equipment_type", models.CharField(max_length=255)),
                (
                    "equipment_model",
                    models.CharField(
                        choices=[
                            ("lease", "lease"),
                            ("outright purchase", "outright purchase"),
                            ("placement", "placement"),
                        ],
                        default="lease",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("broken", "broken"),
                            ("repaired", "repaired"),
                            ("out of service", "out of service"),
                            ("under maintenance", "under maintenance"),
                        ],
                        default="active",
                        max_length=255,
                    ),
                ),
                ("status_remarks", models.TextField(blank=True, null=True)),
                (
                    "reported_on",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="update date and time",
                    ),
                ),
                (
                    "transfer_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "repaired_on",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="update date and time",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
