# Generated by Django 4.1.2 on 2022-11-14 12:33

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="transfer_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("broken", "broken"),
                    ("repaired", "repaired"),
                    ("out of service", "out of service"),
                    ("under maintenance", "under maintenance"),
                ],
                default="active",
                max_length=255,
            ),
        ),
    ]
