# Generated by Django 4.1.2 on 2023-02-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipments", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the equipment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier",
                on_delete=django.db.models.deletion.PROTECT,
                to="suppliers.supplier",
            ),
        ),
    ]
