# Generated by Django 4.1.2 on 2022-10-25 11:34

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=255, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
