# Generated by Django 4.1.2 on 2022-10-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)

import app.users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        max_length=255, verbose_name="Contact Person Name"
                    ),
                ),
                (
                    "contact_person_phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            app.users.validators.phone_number_validator
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "contact_person_email",
                    models.EmailField(
                        max_length=255, verbose_name="Contact Person Email"
                    ),
                ),
                (
                    "contact_person_address",
                    models.CharField(
                        max_length=255, verbose_name="Contact Person Address"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                ("supplier_address", models.CharField(max_length=255)),
                (
                    "supplier_contact",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            app.users.validators.phone_number_validator
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("supplier_email", models.EmailField(max_length=255)),
                ("supplier_website", models.CharField(max_length=255)),
                ("supplier_remarks", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the supplier",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-updated_at"),
                "abstract": False,
            },
        ),
    ]
